package com.github.treesitter;

public enum CompilerError {
  NONE,
  INVALID_GRAMMAR,
  INVALID_REGEX,
  UNDEFINED_SYMBOL,
  INVALID_EXTRA_TOKEN,
  INVALID_EXTERNAL_TOKEN,
  LEX_CONFLICT,
  PARSE_CONFLICT,
  EPSILON_RULE,
  INVALID_TOKEN_CONTENTS,
  INVALID_RULE_NAME,
  INVALID_WORD_RULE
}
